[0.11.0] Migration: `next-translate` in Account
suankularb-wittayalai-school/mysk-frontend pull request #297
Opened 2024-06-01 09:31 UTC by SiravitPhokeed

## Code Changes
- Migrated `account.json` to `next-translate`
  Resolves FRO-161 [(link)](https://linear.app/skiso/issue/FRO-161/migrate-lookupjson)

## Preview
Preview available at https://pr3.mysk.school/.

2024-06-02 12:00 UTC, Sun-52 requested changes
The translation of the report issue button without children and the report issue dialog don't work in account pages. 

2024-06-03 10:23 UTC, SiravitPhokeed commented
@Nubboyy What component?

@Sun-52 The Report Issue Dialog component is simply not migrated yet. Do you think that migration should be done in this PR now? I wanted to keep these PRs small so you’re comfortable reading them in one sitting, but I can migrate it now if you think I should.

2024-06-03 10:54 UTC, Sun-52 commented
@SiravitPhokeed I was only thinking that everything on the about page should be working and I forgot to think that other parts would be migrated in later PR. Sorry.

2024-06-03 10:55 UTC, SiravitPhokeed commented
> I was only thinking that everything on the about page should be working

@Sun-52 You’re right to do that. Please do continue to be vigilant for any broken parts because they may well not be intentional.

2024-06-04 12:22 UTC, SiravitPhokeed commented on translations/account/certificates/receivingOrderDialog/th.json
> +  "desc": "นักเรียนเป็นคนที่ {{order}} ที่ได้รับประกาศเกียรติคุณ โปรดจำตัวเลขนี้เพราะโต๊ะลงทะเบียนจะแบ่งตามลำดับนี้",
`number` is not a variable. It‘s a [formatter](https://www.i18next.com/translation-function/formatting#number). Line 3 you cited is missing the formatter, which is incorrect.

2024-06-04 13:55 UTC, SiravitPhokeed commented
@Nubboyy @Sun-52 Sorry about that! Have another look.

2024-06-06 04:08 UTC, merged